version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  testdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: app
      POSTGRES_DB: test
    ports:
      - "5433:5432"
